// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kskccdhjrxueitellwak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtza2NjZGhqcnh1ZWl0ZWxsd2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODEwNjAsImV4cCI6MjA3MDA1NzA2MH0.HdqoWaUr_A5jU05NG-z7v9Pspy_ZVECFAbnTAopTP58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});