// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdrmcujckwosdvdjkpem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdkcm1jdWpja3dvc2R2ZGprcGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDE4NTEsImV4cCI6MjA3MDA3Nzg1MX0.50NUw5GUdcfMu9ZYQAbd03vjDW38Bg2dYd-OGllUuks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});